# Generated by Django 4.1.3 on 2023-03-07 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authmod", "0001_initial"),
        (
            "accounts",
            "0004_remove_companyuser_company_remove_companyuser_user_and_more",
        ),
    ]

    operations = [
        migrations.DeleteModel(
            name="CompanyUser",
        ),
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.ForeignKey(
                blank=True,
                default=1,
                help_text="The role that user has. A user will get all permissions granted to their role",
                on_delete=django.db.models.deletion.PROTECT,
                to="authmod.role",
                verbose_name="roles",
            ),
            preserve_default=False,
        ),
    ]
