# Generated by Django 4.1.3 on 2023-03-07 14:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_delete_companyuser_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.IntegerField(
                choices=[(1, "CompanyUser"), (2, "VendorUser")], default=1
            ),
        ),
    ]
